#!/usr/bin/env perl
use strict;
use warnings;
use utf8;
use Parcel::CLI;
Parcel::CLI->new->run(@ARGV);

__END__

=head1 SYNOPSIS

    % parcel help

    # Make 02packages.details.txt from cpanfile
    % parcel index

    # Make local library directory from 02packages.details.txt
    % parcel install

    # Run the script under the Parcel environment
    % parcel exec -Ilib -- perl script/foo

=head1 HOW IT WORKS
