#!/usr/bin/env perl
use strict;
use warnings;
use utf8;

use Getopt::Long;
use File::Path;

use Parcel;
use Parcel::Installer;
use Parcel::Downloader;

&main; exit;

# Install packages from local mirror
sub CMD_install {
    my $local = 'local/';
    my $target = '.';
    my $local_mirror_dir = 'cpan/';

    Getopt::Long::Parser->new(
        config => [qw(posix_default no_ignore_case auto_help)]
    )->getoptions(
        version => sub {
            print "Parcel: $Parcel::VERSION\n";
            exit 0;
        },
        local          => \$local,
        target         => \$target,
        'local-mirror' => \$local_mirror_dir,
    );

    # Download tar balls
    Parcel::Downloader->new(local_mirror => $local_mirror_dir)->download();

    # And install it.
    Parcel::Installer->new(local_mirror => $local_mirror_dir, target => $target, local => $local)->install();
}

__END__

=head1 NAME

parcel-install - Install modules

=head1 SYNOPSIS

    % parcel install
        
        --local=local/         local library directory
        --target=.             application directory
        --local-mirror=cpan/   local mirror directory 

=head1 What?

Yet another library manager for Perl applications.

