#!/usr/bin/env perl
use strict;
use warnings;
use utf8;

use Getopt::Long;
use File::Path;
use Pod::Usage;

use Parcel;
use Parcel::Installer;
use Parcel::Downloader;
use Parcel::Indexer;

&main; exit;

sub main {
    my $subcmd = shift @ARGV || 'help';

    my $version;
    my $p = Getopt::Long::Parser->new(
        config => [qw(posix_default no_ignore_case auto_help pass_through)]
    );
    $p->getoptions(
        'v|version' => sub { $subcmd = 'version' },,
    );

    $subcmd =~ s!-!_!g;
    my $meth = "CMD_$subcmd";
    __PACKAGE__->$meth(@ARGV);
}

sub run {
    my @args = @_;
    print "[run] @args\n";
    system(@args) == 0 or exit;
}

sub opt_parser {
    my $p = Getopt::Long::Parser->new(
        config => [qw(posix_default no_ignore_case auto_help)]
    );
}

sub CMD_help {
    pod2usage(1);
}

sub CMD_index {
    my $local_mirror_dir = 'cpan';

    my $target = '.';
    opt_parser()->getoptions(
        target => \$target,
        'local-mirror' => \$local_mirror_dir,
    );

    Parcel::Indexer->new(local_mirror => $local_mirror_dir, target => $target)->do_index();
}

# Install packages from local mirror
sub CMD_install {
    my $local = 'local/';
    my $target = '.';
    my $local_mirror_dir = 'cpan/';
    opt_parser()->getoptions(
        local => \$local,
        target => \$target,
        'local-mirror' => \$local_mirror_dir,
    );

    # Download tar balls
    Parcel::Downloader->new(local_mirror => $local_mirror_dir)->download();

    # And install it.
    Parcel::Installer->new(local_mirror => $local_mirror_dir, target => $target, local => $local)->install();
}

__END__

=head1 NAME

parcel - Yet another CPAN module manager for applications

=head1 SYNOPSIS

Create local mirror from CPAN.

    % parcel index

And install to local/ from local mirror.

    % parcel install

=head1 What?

Yet another library manager for Perl applications.

=head1 FAQ

=over 4

=item Should I include tar balls in repository?

Parcel downloads tar balls from CPAN/BackPAN if it does not exist.

=item How do I display diffs from 02packages.details.txt.gz?

Run following command.

    $ git config --global diff.gzcat.textconv gzcat

And put following contents to C<.gitattributes> or C<~/.config/git/attributes>.

    /02packages.details.txt.gz diff=gzcat

=back
